/**
 * som-dados.js - Gerenciador de Áudio e Efeitos Sonoros de Rolagem de Dados
 * 
 * Reproduz o áudio oficial de rolagem de dados RPG gravado
 * (freesound_community-rpg-dice-rolling-95182.mp3) utilizando Web Audio API
 * com AudioBuffer pré-decodificado em memória (latência zero, polifônico e
 * 100% imune a restrições de CSP do Google Meet).
 */

const AUDIO_ROLAGEM_BASE64 = '//PkZAAf0hEYVKY8AIAAA0gBQAAAEgJZ/AIAAgAAAAHCxHq/2CQJBMcYo2vX3xYYIeo2fDxWKxWRL3Y1er1er38eJSlPDfx8M87AnEMUDI8pe97/FHjxXq9/f/3fqxkiZvukCI/fv36vV7/cBXq9/e977o/j4pljV7Pt/HxTUNXnOTsQwTQXAhB0MmX7948ePFYrGSZjQxQRIb+PZgQw0zTNND0PV7PuAr1ezv499+9MsaHmmaajZ93fq9D0PUbO/fqyZTnOaZ1s79jQxQMkTMN+/w/snDQNBQRIavOhQVT5pk7Lmq2w0zrc2xOKBkqrzQNA6EMVjJEy/Qw5DQJwPQQguCobzQJwaB0KB5q93jygAACFLAwyhoucANpkTJ2yA8YM0MPITBAcHbAEZLAczYcZfoNEI00zc2hgxBADIDmqzPWDJkwSSMmGNUHNWHT8e1I07LYEBwRBFQ4OGrvQIpXmHDoXoXgAMGDBUMCkxh2xYDApMp5MZT4YOCxAaJ/QwemgwQHNFJIcH+L7AwaZgigT/4OcowwYuhCVpqdLUgwWSAocLDk2gVWFCYJPeqYrAiEAVgfMCQBAYFDPSPST295cgHDywqFT6RhcksBkjQSHM8HLlmhQNVau1QQAVSCE//PkZMw1ahMuAM1oAAAAA0gBgAAACYAiHAsmKKzA4gxRRpThFczwpFUILrhU59FYKC/RWUaRWRUMWLNmyLB9q/tVEIBq7VGqtUVMVgVSqlLTp5/+SBZadPNLDLIClzLlwMvQLLblpUCk2ECy0paVAorLlgsBGIGWgQuWC3psoFoqqNFgUEP0VkVggsiuiopyiqispyispyirKgMvLT9MuVLTpZoFFpE8NJ/lr0CzLlS15actvW//LSmXYFguBGBaUtKZZgWlQKTZLSpsAQsgWWCwFLegUgX/+ioFBYQVU4UaUaCsYIKlYpFZFVFVRpFRTlRtFVU36zNLFgNLmLGBjy2Y8ZjiKJMAgITPxEGBhhooJIg4bAERMtIhQqBR4ZAA1Y795RAwwYFDAPJLSHKYAMwWuEYcypQ0SNaJYWmaDHsIGBAm+IG+IJIggmCn4qTMkTVKZAgICAcANAvMOrMmfFq4JJFg+04SHpWqRUmODBQ++b4JGpGFygUnBB41QY2wZJNnAFLIFlpQIWA2JAtAssCvU48Ki0VQgoWGAELgbGbEumwbEuBy5lywHKFpECy03mWLgUuBl5ixYQ9RXRWCCinCnBihSjYAMFkQxlBqEUGl0BgMGISsWo0o0pyioo2i//PkZOs3ihUgAM3oAAAAA0gBgAAAqisEFTFC0VgqKKwJWBVK1dq4cAEAAOBGRIGQQNWEIFnSSLOHxZ174gocCh7OE20jEC02S0pacyzEsFi0xacy5YDLi0oGWgZamyBlxWW8tOBl3gQsmz4GXIFIFFpE2PLSJslZf0CgMsLBdAoCli0hacDLyssgUWlQKLTAbB5WKRXMUfU4CCxixRWLMULU5RUU58ILhBbwqKMULU4RW//QLQKApctOWnLTFbErL/6bP+gX6bKbH//+VikVjFi0VwqLUaRVKxanKnKnH+EF0V0VPU5VTEFNRTMuMTAwVVVVVVVVVVVVVSoBDLDFYTMQS+iYoXDhAcywwRGDaQDBAkVCw1PXBNXhPpUEQo2pgxqoTa7jNdk8xohDE1cMgkAwWXDE41MgkAxqhTSZ3MnhkwwNTQhcNCvE8lJzO5qACgATuMajQxOXTNYnMTCYrIJiYnGThMahLpk4aGTi6aEDABBRgoMmXAyWAUZBLhqETGDQEVhYxCITMAMMQkEyCFywGAAJgEuTBY0AQUEicAQwYZBZicMIEUCBhkaAIYAATGThoZrDJiYuGahoZrDICGJgoTGCyAIiCZADJhkaGGBqYKE5goFrtbMgRAQVXc5D//PkZOY2JetCYM1wAAAAA0gBgAAAlmAgEYCAQQGDFYXGgPBisACJoCCwBBRgsMF+y+xfVAku1Ai2X13NkXZ/+2Zd6BEsmgTXeX0AQULAKAQUXeAgou1AkX5bO2ZshZIAgpdpfQAgpd3tk////9s7ZF2iMMmJwWJDEwWC13GGQWX6AQUKwWuxd4kFC+4CC5fUBBcskgRL7F+iybZSyKBJdq7WyLubI2f12//tlXd/tkbL////7Zy/bZC/C7/9s3+2dsi7F2Ls9sy72z//rtbJ/tlbM2X/bI2X2ye2Rd3tlXaqTEFNRTMuMTAwqgmCw8FAWFQWZSYpowplgpFgpmGikYaRhiYjGJwKWCOYbKRhsNmUkYZTKZhsNmxUYYaKRlJGmGg0YaKZv1iHNSkVhs0aUisNGGg0V94353zfgaNGhow2Ujt5SMNIw34UzRjENGI00Y/DfqMN+BosBsymjTYhSN+BsykGisplhiGUymaMKRWGjDQbMNI0w0GzKQaMpFMw2xDKYaLCMNihosIwrKZowNGGw2YbKZhoNmGykWA2YaKZWGjDQbMNhsymGisNlgpGUykZTDZYDRYDRhsNlYbMpBsw0GzDQbMNhsw0GysNGGykYaDRYDZYKRhoNmUw2WA0//PkZPU4EfciAe5wAAAAA0gBwAAAVhsrKRWUisNGGg2YbDZYKZhopGGw2YbDRhsNlgNFYaLAbKw0YbDRYDX//+YFAn////lYELAE///ywBSsCFgCf5gUClYFKwIWAKYEAvmBQIVgUrAhgUC+WAIWAKWAIWAIVgUrAv+WAJ5gQC+VgQrApWBSwBCwBSsCorf6nCKyKqnCnPoq+o2o0pwpwpx6jfqcepx///qN/6nCKqjX/6nPqcf6nP+ir6nH/6jX///6nP//qc+o2px7VlS+qdqrVlStWap/tX/1StUap7V6MO8f02Lx/DH9DuM/gpsrKaMpsT4xpxpzGmUvLBtRifn8mJ+U2Yn5TRlNFNlYnxlNFNFaOxtgo7GRYjuZFpFhWjsWEdjR3bAMtuMorLbKy2zXSLbMtstsoW2MtrrorvDNdNdIy2i2jXTLbMtpdPZrprpFcZR3hLpGumumZba6RULaLBbZrpXhneFGWVxlFiMoy2y2iwW0WF0ywW0a6UZZltLpmW0W0ZbZbZWW2VltFgtosFtmukW2ZbZbXlZbRrprpGW0W35ltFtlgtvystoy2i2ywW2VltGumukWC2istsrLb/zLaLbMtots10l0ztu2jtq2yu2iu2v87bto7bto//PkZP85sf76AHu10AAAA0gAAAAA7bto7atsrtr/O2rb/wZPgOfz4GT8Dn8/Bk/CM/A59PwjP4RnwHP59A5/PvBk+gbud4Md/8GO4Iu8GO7A3e7uDHfgbud8GO/BjuA3e7sDdzvBjuCLvhF3Ax3wN3O8DdzuBjvBjuwi7oG7nfCLuCLugxZgxZBFZAazWQRWUGLMIrIDWayA1msgNZrP4Gsln//gaDQUIoIIoIGIMIoOBoJBQYguDEFBiDCKCCKCwigv8GIMIoPwMvF8DLxewYXoRL8DL5egZeL8DLxf4ML/wiXqMg3DNIkiNIiDKyDNI0iMgiDMX1VMXhfMXhfMXxfLAvmbBslbAGWTAmWTAGkaRFggisgjYAsjYAsiwwBYYE2AlHzLNgDx6USsszLJgDLKUDx+UTYCUTLMsiwWZyjKBlkwBsCwJYLI2B+45RLM5QYEsSgbAlkWGAMs2ANgSyMsmBLBZGWbAHKLAFbAFgsjx8syssjLJgSsszLIsywWXmwBZlgsjLIsiwWRWWZWWXlZZmWTAlZZFZZlZZ+VsAWCy8yzLMrLIsMCZZFmZZFkWCzLBZFggzIMgjIMgv8rIIyCIL/LBBlZBeVkH5kEQZkGQRiCUBWUJYEAyhEAsCAY//PkZPw6GgkEAK70AAAAA0gBQAAAgiAViD5WIBiAIJiCIH/5YED//ywFn/5YCzysLP////8wtCwwtC0sBaYWhZ//5YC3/8sBaWAs/ywFhYC3/8rCz//ysLCwFn/5YC0sBaVhYVg2Vg0Vg2YNg2WAaMGwaKwb/ysG/KwaKwbLANeVg2WAbLANf/lYNFgGv//Kwa/ysGysGysG/LANlYN+WAa//LANf5YBv///8sA2Vg0WAbKwb8rBr/8sA1/lgGisG/8wOA7zA8Dv//KwP///zA4DzA4DzA8D/8sAcWAP8wOA8rA7/KwO8rA6CREcgSFTGwCMVgMxYTTMqjDAGGBIv6yo1GTTu77cgsCowEGi5Bp8bmDQsMhAYBAFBnhANQccbzObQm0czLcFgWDAODB0DAsMFwCMDACVUckx3HcwVT42gNozbNosAOGBaYDAMFgpKwoMDQCVhGQCMAwXMDADOBI2NbioNbk+NPkMMqAUGgEViGAMMAgDckIAZBIzqgoVEFdGVBUGbRtGVAKGVJUlhDDT4qFVwgBVOIO9VeDIMVWcpTlWJWCDTBUFDKhDDQwdjEcRjQxbjT4qDW5PlPxt8nTZ26UYjEbdJTp1Y2ziM0EYfAzaBQxHEcrEcxGEYxGB//PkZPY5hg8kUM50AAAAA0gBgAAAQwUBQwUBQrBT/jbo0NFRRmMUFBRvh9D/0Pxugo3Ro3TKwV8rBQsAqYjgqYKAqYjjuY7gqYjiOY7lSY7gqZUlTep3heR/6eKxa5TRanvSSliT4qf+ho41RUEZjD5Rn6CMUJlSO5iOCplSO5iOCvmI4jmI4K+YKgqYKgqVgr5YBUwVBUwUBQsAr/xiM0PxijoaKhfCioIxRUVHRf/vjGnzjVDRUcZoaKMUdHQUH0P0f/5g6AJg4ABgCDpg6AJWABgCDpg6APlgASsATAAACwAJWAJWABgCANVMQU1FMy4xMFgADIwY0xxDgUwIeR3MnBDZWQ0FNMqEjEzcsiWuPZXzIXw37lN+FywtGZhZmnLnucscR3JopWGioj5mlnGzzQYFI5mhnGrFYfb3Ju+6GRgKZHVh7kCmaTQWCOWBOasRZkYCmmDIb+MpzMYAbMGZVmbvRZu4TGaCMZHAhkd3mRneViYxOJisCGRiObNJZkslG5CUZKJZpl/Gfj+YnAhgUjmaBOWBOZHI5gUClgFmCxkYKBaK5h4PIqmMD8BRgZLTJmUyGFz8Z+WZhcYGBSOZoApgRFmBSP5icTGBQIVgQwIBTAgnLAE8wIBSsCGf//PkZOw26fs6oM3wAAAAA0gBgAAACeYBCBiEQGEQiYBEKpmqBwBDhCVhAwCIBAAWrhwBVKIAC1X0k3wTbZ2m0+L5/4gCBgEIhwAMABEsBAQBExAETF4QEIRDiCYRHxhAQhUFIreisiso0pyYKBajanH/74Ph74////+YTAxhMbFgDGEwMWAMCgaWAkkmm2XIURTbLkpGJtggDs6Ta98mcf//////9G+30H0X0f0P///QLQCwHGgamMtVBkLAaDVO3ITFclyExVOnLg+DoP////kv+0n/+SfJP///////6ChVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVgCgjGziMUWBYWDpilYYy4Ywwcw4cMXJjGHDFYErAG7OBZ2mP/nGKGUKmU7mUKmUKmUKmUKHG7gfcoB94wGUKAwrCJQDjRwOPGCJQGRgjGA48YDKlAPsU//PkZFckSfEuV+1QAAAAA0gBwAAAAysaESoRKAwoBx44GUKgfaODI4MKQiVCJSBlYwGVKBEoESoMKAZWMBlY/CJUGFQONHBgADAnQiAAwIADAgQMCdAwBzwYABh0DOAYMA8InAYdAzoAIgYMA/GILoQWF0ILjFEFYN0hBYQVGIFjwgtGLi5hcxCcOgFzkKP4/EKPwdMIoQo/C5xFhcwuUhCFi5SFFzEKP+LnkKQg/x+/8hIuchCFEWFyfj8Qsf4/4/yE4/R/8lslf5L8l8l5Lkv5KfJSLkyFkKPw/8fiEx/VTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWMkCFhkYoUo0WmAy0Cli0gFlFgu1UsADIATCpjChTTBQkads8YsV4EYGWLAQsVrPLC01nU1iwDB4OBgOgYPBwGDweBjoyAZ1OgRFoGLBZgwWAYtFgGdBYDBbhEWBFfAwWgYsOoGOwcEQeB//PkZGomrgskU61UAAAAA0gBQAAAg4HhEHgwdAwHBEHAYPB4RB2DAcDAcBjsHBEHAYOB8Ig4GA8Ig6DAeEQfhEdgY6B4MBwGDwcDAfBgPBgOAFCwNg+DYPhhwiFguuDYP4Ng78NWCrFYDVoqxV8VQrP43Mbo3huDfjfxvjdxuQwKN8UDjcFAjdG4N2N8b0b8UEKCG/G8N0b3igY3RQWPxbIoWyKyKkVLQ5MixFi0Wy0WiyWix5YLZbywP35C/kJ//H8hB/5CCqFWGrw1YKuKsNWCr4qorIqxVhq8NX+KvxVKTEFNRaqqqoAACAJJAZNC5WBzCwMVhMdlwzcTCwC2yJnmCwGaSLgZaBgBOQQAAMFB2XJnT276BMsAFmBMAiYE4Exg1AqGEwCqZLyTBl0BXrvAABQAALXaYTACAOBOMDwBAwmAJjFkJ3MkkU8ySSBTHtLRXcgSbKu5sxgTgT+YEwCAMARBwJ5iFhXmQKKeYnIE5inA1FYQfuUrD7kweDgIysBBRMwEQEQYAgDgIDCvA9MK8GswxgrjCCCCMCcBEwPQa39kz+Fyn/k8kEgMF3lkAEAoX3bP5g3ADmCYAsYWoUZhJhRmB0C4FwBzAWA6kj/fJvf//k/qMFYCCjKjCARR//PkZPg4fhU09c54AAAAA0gBgAAANRlRkMB1MG8G8wKATTAGBMMBcDsrAXKwTCsDswTQKP///5JJ///9RlAOokowox/qMKJqMqMmAsBSFwFguAMGAXlgBcwKAFywAsYFIFIYAeVgUBgFxgUgLf/yf///////+DnLcuDIOg6D/cj/g/3Lg/wEAqAACmzCQJwCBMKwGGzl913iQCjZCwAUIwCxEAUIwCkCP///////////////J///9/5JJpNJ///f////bIgQXb6BIrALMBgAovw2dd5fVsi7y+pfoBAKLsXfTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVRNpKVIoJmDiZWPFYWYUFhB4YMJviKgxjQ2alGmNDRYUzUow43EOgQToP8/5BLFAV0JYQDoaA0FAOhoANQEEDIBBhFQAwgwiQANQqADIChAyCQIMIMDIBBAyCoAiQQiQQMgEEDIJAwMNBsDDQbwiGg//PkZHAnfgc2AO3UAAAAA0gBwAAAMplIIhoDDYaCIbAyAoQNQEEGEDCJAAyAQQMgEEGED+BhoNgYaDWDA2EQ2BhoNgYaDYGJwKBiYTgZGE4GBAKBgQCgYEAoRAgMAoGBAKBgUCcGAUDAoEiggwMN6N6N0UCN6N0b43RQMb+N0UCN8booEUCKBFAigRQMbgoIb4oL43Y38bw3o38UCKBFAjeG6KBG9igRvDfxujdighv8RQLhguGC4X////5KeSnkrJaSpKSVHN5KDnDmkt8unS6XS7zp4un/5wunC8Xi8Xi8TEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqowEBVKHABiwuBmMxYXMODzDg8w86MWFzFhcCC5h4cZ2HGHHZYvystMtLDDw85GQKw4w+QKy0ywtN0LTvnQ3UsAxYLYMX4GLDoERZAy+XwMvF8Il+DC+ES+Bl4vgw6AYsFoGLToBr8WgwWBE6wMWnUD//PkZHAnbgsmAK3UAAAAA0gBQAAAOh1Bh0BgtAxaLAMWi0GCwDFgtCIsAxaLAiDgYDwMHg4DBwOAweDwYOgMHDsGA4GA8Ig+AKFwbB4AgWAGFoAwtAFCwYcMNC64Ng+DYOBgXBgWDDBdeF1oXXhdcLrg2DAbB0MNFWEQAA0ABWRViqDVwatisCr/xcnkLi5eLli5CFH7FzC5SEFzh+gueQpCj9IWQshI/C5R+H8fouWPw/R+H8hBcg/yF+Qo/D9Fzi55CyFj/5Cf////H7j+Qn8s5FZZIqWpFS0Wyx/8i8tVTEFNRTMuMTAwVVVVVVVVVVVVBQGAkBzAYEzFkNkVjB8lwgPisMzOYqjKoqjAsWjNMbg4AjCAMDSNmzOcMza5hjFuTAqGZg8GRg8BZi0X5nPJh/hHRocfZnM6wSTJg+D4QWhhkGRg8GQQHxs2N5kEGZzAN5i01xzCNxkuXxi17hgUDwUB4wKAsrAswKB43rIMIX01eL8znKoy+Ecy+Zo2HFowKKszSKoyrL8IDxFcwLApTkKgWo0EUqZLiOEAoZfg+EFoYjgWZzHOaHiMYFkGYti0YZl8YPF975Pmkkzh82cmI4FmD4PmDwZGDwZGGYthALBUHzAoMjEcHggPwqGR//PkZO03ChUuAM70AAAAA0gBgAAAi2GYUAowfAp8XyfB8Xy98XzfMOCIOAEsACHAAYAgCHAGqQwABAwBBAsAWo2o2o0YFAUFQKCAUMCgeKwffL3z//98P//FgMMEgGMBgSBIDlyPfN8mcvn/mBQFBQCggjzAoCgoBYQCqnCKijf+o1//////////7OPfH2dpHvgzv/Zwzh8WcPk+fvm+b4Pmkmzh80jVEUkPZ2+Hs7//98v//98///////98mc//vk+bOmcs6Z0zl8Hz/////2cM698///Z375vkzt8f/3wVTEFNRVVVAILQBhEARkECZgGERg2SRgGBQJCsxcDQw0JMw7EIxLEswTBoEg2bqmQb9c+Z3MOY+v0YqhcYqGSYd4PZlJmpGgiTYYdwsJjDBRmIqLAYFwF5g9g9mFEHcYnZSRmDj9GMOJ0YZAsJgEBRmFGFEYipNhgEA9GFEBeYUQF5gqAXmBeGQYdw/Zk2DqmHeAQYKgFxg9iKmD6BcYKoKpgXgEmASBf4MCCKwgwcD2DAJjBUBVMFUO8wLgojAuFhMHsC4wCAezCiDvMGoFUwagJzAmBVMCYJkwJgETARAnMAsCcSAxQIGBqAWgRL6GAyCeJBqCIFwwGATi/SBErA//PkZPk4kb8oBs74AAAAA0gBgAAAnMCcAswCgCxGAwAgaQEBgIwCyyJgBANKIFgAseAVDgJFEPVIqd/WrqmaqqYwAwEhCAWjd9Jfv0iN6AFLuMr6o3RfKgjNEkeYEQAZgBABmAUBWYDQBRgNgNGAGAEIAA38auhs/kmZIqZU6pZLJpP7IpNJ5KzlBdMSMe6EZjEa/6KNUNFQuqkamKzpfxYABo1/K2xuNPjJZM1SSP9JmTyRkDVmTSWSv4/7JH8k7+/JX8k8kf35JJH8ZLJn9ZBJpJJf//9/ZL8kkkn+S/JFTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUwOKSsUFkAEMTJpdMLk0v2JE9WEaAht1MnTioDBMYQHijJmsemz4SZ3HRhQFAYBxhQHRWHZg4HZiyDxnaHZrFcB+ZGBg4DpjsAJg4LBgAABh2SZYFgwcDowcB03ZWI6IX41/X8+wdgwdDssDsYAACYsA6WAdMAAAMWA7MWABKw7MAQAMO1/NuztMdiTMOzONYjsMJwQBwQmE4ImHoIA4IkAgNBFAKDQRMEQRUZMEQRMsTsNYkIMkgANJzPMOySNCCwU7U+GAamKp0p9TtT5YAZMUrAZTtT6nzB0djHYHDD//PkZN81ShUsAM50AAAAA0gBgAAAsWTFgdzLEkzAAOjM8WYzQ0Xxug91qOi+ijLpxugdCMBcFgwLDDsTTF0FzCgKDLUgTDsFzBcBzFwOpLJJK1f39+TSeTSST0EboXx+joPjf/4UAMaAcwNAMKBAYQAYisEAIiorE5IQA40FlFRUFH9D9BQ/9HR0H////0fxr///+hoyybZy/YAAovwX0L8LvL8NlL9l9QEC67ECZZD/////////////////////////////g5WBRtWODXKVgVjchFQrANFRWBVRWFWNyXLVMKxMMBxAMBgHKwfMBwTMQBZMKQVMYzaMRgzMRgyCC0MChHMjJQOF2nMrRGMzgnM/E1NNTFNbzEMjXeNpz9M/GnNNDEM/RUKwEMrSKMRzPNXygNXihM/ihNX+YMGyNMxDFM/E1LBimKZ+GmopGDaaGYgNnzKvG3kOmr4glZQGICvGf4gFZ/mUIglYgFYgmmopFgjCwDRYBsrBsyKM4wmIszvEYyLGgwnIs0yGkwnIownCYwEIswFGkxoAQxpEYwfB5TksA+FALCgFhUCjM4zzIsRjAUaTCYJzCYRzEYRzGkBTCcBDAUBCwAphOAhWAhYEcwEAQKgWEAopyYFg8pyi//PkZP86IhMuAM70AAAAA0gBgAAAqpyWAnMJgEMBBHMJhpMiiLKwFMBAFMBAEMBAELAFqcBQCggF0VzAsCgoBSKyjTORUB02kknzST9nT5AIGl3FqWmtOUNaY/iVLZF2oBWzyWStNf1s3tKf1pK7mkqJNLkkl9/n8f6SSf/XcX0UPaUX6SqSuUOQ4Fq1DWlP+/slkjZmypVKSk/v80qTfJJL8nk/yW9JYjciP0v092npqa9eXNEotEaV/ZNSxFnMRpHCuRaSxJ/r//925e+luf9N93/u3P////vXfuUt3/pr9Jf+9T/cA5gwXmLywITSZHbwsCzASXlpmAZmqAmaIW5xcKA6gGBk0dsFpuNwGHxEcL8p0zkmPinGgoDGkJvGFKIGCSEmu5jmrjJG9RuHMiamhYZgK9zDgRgcUBgGLBi0hZgsbxoIYhvFWBw84hi8WRkexgOcoz8BgyOK0ycA0w2DQylXcwkHMz+KoxZGUwBGM0+hgICwwTJ8yQA4oGMyuFEwADEwbLwyJFAOKcwwDgxNDYRjUYlA+ZThiYIh0YMhWZDlOYvkCYqB4FwfL+GCojGCwFgEClRGAIXGCIoGCoBhUJwKCosHYMEAdBQiCUs2AQQMAwJMCQfMDANBwVsr//PkZPk5ZhkkAc50AAAAA0gBgAAABwFlAVDQTpvCQfrSEAOsAcxRp/SsIUy1Q2UrgAALUHLbqJAtAQWAcoEcmBcRgXihzafKZeylljII5bf5zGv0LOEQ08mBu4j+nWo3MM+k88+pf5oKDlZt00H5hh7XCrSKAaSYhqhfmkfp0Wo/qER+x8PsydqDYLcHCHopA+FBQwbResaLyp/INj8/Dzoy6Wy6T2Ira//ygFj03LV2SyNUsFTFpzpRUu7//t/eerr0rOl76QZDUBVH+kLq4Pdr/yy+/JWb15UxOOto4FaEOpMPfPWdqgCBgEMVk9MIwFGhUBQAmKYFmKy3GYTLmNwtmMYlmHpGCREnCQ4nnamm7tsGBTSGWpWGiw3GT8HsYMwvBouF/mLyL4YrwexjQinGDOCOYFoPRlYgVmNULkYTQt5iGEMmUOnwYeoc5g5AmmD+IQYpoPBgDCBGKiCwYDIc5gAkSGSOWWYHhD5kPgvmDCA0YAobBj3g8GC4EsBgizAKAzMBsE4x0QezAcClMLsCsCALmBoAWBAADA9CyMM0FkwLwBAgCswWAOjA+BvMFYBswDAAh4HEEAdkoFpMHGYLYBJgcAYkIAoIAaMA0B8wJQDxICtUCQ6wpgJAHq+B//PkZPg57hkmAc74AAAAA0gBgAAAgBbE09UEpEBESAHlYCSnSD4MAFRpVuLmqCsVUxbqhNIQDEwVLlh09VnpjLAtXTBedwHgpVeMpgtH6HVgmnJypaoSiQAVJIuS3ZDGWwLGJ2Ove99JGorU7/2p+rgmkwtoqKsNJi2nsg2QUL5uxFZ+Q4YwHPPbDcufXT0T7uxCKOjRa+le6zJYrL78qh6gcph6w07/yRvZHMyd0O0OUDuzFOcehd0itx3tnspblDWdaOyLX+1h+f7/IO3etf8277uf8kk2/99Wp9vNgWGi+nq7/1ZO/V74nF9VgAADS4IBi0BRocVZh+Nhk2J5gAABl2bJkaAJmQVRi+PhkYbBv6dJmSqpqqyZrGVRpMbBh+k5x2RhkYXYgIdMKsNkxVAfTAvA+MIwLsw2A2TC6C6MLsksylxNRAEYYZIEJhkAfGD6F0YRok5gngImC8AAYPoCBhVh8mIMQYYXQg5oyGJFYqpgQgvGC+ACYTYH5gXAAmEaE0YVYCAhAADgvDAAAQMIwf0x/RBzFzFVMF8D4wLwjTBOA+DgIjARBeaqHAAFgBAOAgDgXDAgAhDgXTAQAADgITDYARMLsI0wLwATABAAMBEC8wXwAVSlgAAsAA+1//PkZPM5wgcgps74AAAAA0gBgAAAcQAIqlKwAGqqkEAALVzABAAEAAJgQAIGBAAgWAASwACIQADAAAQVM+aRySCbbOXzZ0+f+qX1TNWaoqdqvpIJJvkKADM5MCoAYwBwHwUBOYCQCXtX9qipmrNW9Uyp1StXav/+1ZqrVmqf7VmqmBgAsWlMBYBYrAWQLAwFibKBRaf02E2UknzfH2dvh/vk+D4f74Pk+fs5//fL//3xfF83y/2qqnaq1dqrVWre1b/ao1Zq6pvar//7VGr//ql9q////////7VPao1T2re1dq3//////tW//9Un//tUMH8BYw/gszC8APMA8ZYw/w/ywBiZOAy5hICJmM0BaYqIqBhIh0mB2LUZXy8plfKpGIOc0ZFoOhYEHMHQL4wvidzK/ItN5xC0wLTUDNRFQMeIQkwvwdDAsFQMZsQcyLEdzGaFRLAzRmEtgGIMBaYgwFhWKgViEGDKB0YnwMpYESMDoT4z+THjE+HDMkUpowDgkTCQDpMQkZoxmxUDB1B1MHQQcwLALCsHUwLQLfKwLDB0AsMH8JkwfgMTCyCZLSAUEswMAfk2TBLAXMDEEowMAF/AwSoCCgLmGBoAMAQBlPFzhgAYwNQGAwCNCNaPoNiE//PkZPA5+hcaAM94AAAAA0gBgAAABAwAQASwAAHAAqkEAAJYABQYAQByYynbluQp0HAQKkVMYAACBgAgAGACAgWAEfDgAkIFrOSXOAQBynblLVWktFaa1fcn4MWg5QgAAMBEBBU7V2qtX/1TNWau1dTqD/+DIPgxyHLWgp3BrN6L/fpyn4o2BvvRvzBy04O/1OnKgyDVO1OoO9y3ITFWlB0HuTB6noOQZctylqqdQfBsHwfB0Hf6nbkOW5DlrXg34Ngz3K////////9Av////////2qNU/2rKnVI1ZqzVWr/7Vv/2r//tW9qvtW/2r+1b/at7VUBmTCcGvrgGhFEm3QOmycCAxITmcqDBQFTM4kzAFCQaE5giCJzO0Bm06ZwI0JWhpjuIxreCpWbZjuVJm3G5wIhhWChm0VBWUZmQPZrCnYOE4yDBEyCGsw8CcwIdQzvKMsD2Y9HeY7rcZtDsaGjsYjJ+a3gqa3DsY7iOYjAqYjDuY9CoZRHeYECoY9j0YXBeYECqYXGSZ3ioZRD2YqAQYuhQYLCYYUCaYuAMmKGAcYLiaVh0GBcViYVguYUAOIg1bIYagWYFgUJBkAgWbIu5dhgUBRfsSBdAiu4vsWALL9lgCiyBfcsl4CDIskA//PkZOs46fkQBM70AAAAA0gBgAAAgxXcX1DANCwL+mIp7wwDiwA6n/THCwDqdJjBcBwuCwYBynYWBZMYLAMp4MA0rAYLgMmKmIgQbKX3bOX6bM2Rsi7S+pfRsi7yybZy/RZBAiuwvqX5bI2ds67kCRZBspfgv0gRXau1spfcsl6jCiSAT1E/UTUTUZUTUYUS9RJRhRNAIgEUS9RlRP0A6jKjIOCNRhAMomomokowomomowol6jCAT1E0AqARAN6Af/KwJKwI8rAjzAgCPLAEeVgR/lYE+WAJ///zAgCPLAEeWAJ///ysCP////////8rBVVAQQzQRzExGMfnwQAAKDMyMqzDwfLAzKw2b8Rh24pm/A0ZGE5gQCGjCl5vyanp7f4VDMwKFoygKAz+V41eKArSI0jII3D6EwLFsKAWFQKCgPGr5/mf5QmIIgmr6vmUB/HDp/GUNtGUNtmBQFormD4PmBQFhAKmf5QlYgmr5/lZQ+eAuEZBTAZBuEWCCLCRmCAAiAAWrqn9UhmIYhkYRhikDRYBswbBvzBoUjI0xSs/DFIUzBsGjTUxZM/zZJK/jS/MJgmKwmMBQFMJgmMJgmMJgEMJwnMaCKMijPMBAnKwnMaQEMJgnMBAmcly3I9y//PkZO43VhUeVM50AAAAA0gBgAAA4NctyFpmE4ClYClgBDAQBPMBAEKwEKwE8wnCYwFCYrAQwEAUwEAXzAUBfMBAFaQ/jTPXe0mTP4/smbI2Z8Xx9nD4vizpnD4M4fN8lOEVlGisC0VQqBSKynCjSKvqNf/s598nxfN8/fJ8XzfNnXvm+X//s7Z2+L4pt++D5ezhnbOWd++b5qIJGPkzlnKRj5pts6URfN8mcM6Z1/vizv3z98WcM7Z2+Xvn///++b4vm+b4M4fB83yZx74/75//////+pwpz///+pyioo2o0kxBTUUzLjEwMKqqqqqqqqqqqqqCmRwWYeBRooCGJwKZpE5kZWmaROYEAhWaTIwFNWKwzQ7zKT8MpFM1aBDVpoOaTU7fNTAQRisizAUrTIIgjDI0jG4HitNDMQxDW6FysGiwDZg0RhkYKZmIKRkYYhikRhtOYpq8fxlCIJiCIJq/zBg2RpWKRWRhg0DRWDRiEfxn8UBlCIPlYgnbZQmUJ/nDp/FgQDEAoCwAhiOExgKExgKAhYAUwmAQwmAQwFEcxHCcsAIYjBMYTAIZiCmZiCmYNikYNikYpg0ZiA0EAoYFgUFALCoFGBYFKNqNFYCGE4TlYClgBSwApgKApgIA//PkZOs23hcqAc50AAAAA0gBgAAAhYGkwmIownAQwmCYxGCcsAIYTgIgGkskf2TSaTP6/gQCiKnqNqchALmBYFqcoqIqmBQFqcqcBUHjAoCysCggFjB8Co2+lCwWMUEbjdBR0cYRU9FT/RX////MCgfKwKRVUaU5UaRWUbU5U4RU+5JJPT3aS5ek8UpH8p6e78mfxpn+2b/kz+yd//kj/yeSLtk0nk8kaa/r+v6/0kad/v9/wfB3wb//Bv/Bv/B//Bn///////////////////B0HwfB8GwdB3uXBn/B8GwdTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUsB8w+CkVDAomMCCcyOBDLZHMjAsxkRzDYbLBTMpo3zQSCNByIyCQfN/kA1AoCwQDIJANQkHzQaCLCCNBIIrQQGQFCESADFABqAgBEg4MQYGg5EByNBgcjQYHI5EBoPhgZBf4RIIMIARIAGQH8BqBQgZBI//PkZHMn0eUsAO5UAAAAA0gBwAAAAGQCADCBCJBhEgBEgBEgQiQAMNhoDKQaAw0G4MDYRDYRDUGBoGFIIhoIlIDDaMA0YUgMNFLCIbCIagwNAwNBENYMEwRAoRE4GBQKEQKDAKEQLgYEAgGBAJhEChEChcPEVEVwuEEU8RUReIoIuIpG8KDFAigxQQYLG8GBQykUGN6N4UDjcxuCghuDfG6N3G8NyN7G6KDG+N7/xv+OZJbJQl5KcliWJbktjmRzI5pKkqXjpdL545l8vlw8dL/OnS8ePl8v5cPF8///JQl1TEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUsE5ggKWCYwUmMEBTBUc1KNP8UzGhsrUjG1M4wbNBQDoUA/7/NA/zQEE6BALCB5WgligNBQTQUA6GgNAoT/kEIkADUJAA1AQQNQKEIkAIkAGIMIoMGIIDQaCA0HIgNB8MIoMD/n9Bj//PkZGcmRgkmAK3UAAAAA0gBQAAAuCLuBjvCP8BjuA3c7wN3O+ESCESAESCDCCBkEgAZAUIMIEIkADUJABhBwYQYRIIMIARIIMIARIAGoVADFCDCBwYQAMgEEDIBBBhAwMNBsDDQbgYbDQMDYRDYGGg2DA1+EQ1EVC4ULhguGiKiLQuGxFBFBF8RXG9G+GBhQIYFigBvigooGN7G8N0bg3RQI3ooIMFfFBcbnG9jcFBDfFBCghQON8bnG7//8b+Nz5KkuOdJUc0liVHMHOHN+OcS/JfkvJbkuSsc3////kuqTEFNMgjUyCagaPTCI8LBUM9HosLsrJ5lUXmVRcZqNRWPTMSiPyWU1G5TcqiMXFQz2LisnmupOV5LzMZiMxmM1GVDFx6MEFQ12TzJ66KyeeTXZiIxGIxGZiEZqJymLxcWBcYIBJgkEleSMn/4sE4rJ5WTjJxOLC6LBPKyd5qIRmYjEYiEZWIysRmCASVgkrBJi8EmCQSYuKpggXFgEmLgSYvBBggEmCRcDicgEQCg4RoBwceTFwJLAILAvMXggwQCDBIIMEAkrCPqMgwIg4QqJKJGEROgEQCAwIGJhN6iajKifoBVElGAcIvUSL9NlXeu1sv+2QvwDQiokYnCKAdR//PkZPw47hcUAM5wAAAAA0gBgAAAgwgECwETE4RMIiddvtnXaX7bM2VdzZV3+uxszZF3tm9diBJsy7C/C7GzKMmEAgDiegHQDqJoBjHgmMTiYyoPEApWJmy+2ds3+2X/9s67fXZ7ZGyLvXau9d7Zl2LtXY2ZsjZWztmXc2UrBJYBBi8E+VgkwSCSsE+YvBJgkEmCQSYvF5ggXGVAQWAQYIBH////////////////////////////+VggxeCSwLjKguMqi8sC4yoLjPYvMEgn/8rBBWCSsEmLgQVi8wQLisEVTEFNRTMuMTAwVVUzFKOZFzFzE0tKMzHywPGlTJvzIY8FhAqVi5WLmTxRtEX4HMzCjM0YLN3Is0WJziAnMCAUwIaTExHLBLLAXMLBcyOBTI4FNFAQyMrDJYXMYDEyWFzMqzQLTYMLBcCBc3QkCsHmOzKYOHRg4Hm6B2YPMhg4dlYPKx0YWC4ECxYCybKbJWMS0wGFxacwsFzJZKLSgQLpsJs+YWGKnCjf//mMQsWlAwsAowAzKLTIFqNeiqYLBSnAVBaKyjf+o0FQUo2o2WA8YzIxh4PoqGChkFQUiuZHBRYDybIECyBfpsIFIFgYWgULeo3/oreiqFQUpwYFE5gQ//PkZPQ4AecQAM3wAAAAA0gBgAAATFgTmJhOWAKWAIVgTzApHMjCcxORisClpi0paYtIgWmz6BaBflpQIF1G////1G/U59RrywDywOzBwOMHDowcDjB4OMHA8wckDMoOLAOMHg4x2ZSsdGDgcVg8rBxYB5g4HlYOMdjosA8sDoweDiwDiwDiwO/8rBxWDv/ywBf//KwJ///lgCf5g4d/5g4dlgy+aRBxpAymZAeYOB/lgHGDweYPHZWDzBwOMHDsx0OysHf//5YBxYBxYBxg8HmDh2WAf5YB/+WAf5WDvLAOTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVZAgcZGBksLAULmMAuBhamwgWgWgUmwmz5gAAlgIGEQAisYfDyK/gQLmFguBhaBAuYWC6bCBRhcLIFIFlpTtdApNktKWkLTFpS0paUDt9Fbwqo1qRVRVCi02ECvQKA7k//PkZF8lSfb6Ce5gAAAAA0gBwAAACi0qbHqlVMqb1TNXaoqZUwcL1TKm//9UrVFSqlVIqZUypVSql9UrVVSql9qipmqqlVK1f1TNX9qqpWre1VUqpWrNWVN7VGr//tVMIFS/7VGrtU9qrVmqKm9U3//+qVqypv////LSoFlpS0paUtKWlTZ/////0Cv8tN/oFFpi0xaUtKWl//QKLTFpkC02P//9AotMmx/oFlpS0paXy0v+WmTZ////9AotMWm/02P9NhAstL/////oFeWlTY/0C////02P9Av/8tKWlTYVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVHA0vQFjBLAwJgLATiXIIrCz6hKLAEWLZ06BBREtFUNbFQlLPqWCWaT1RKVJ4tkFhq4UwiQB1jQWYUdqXC34W+eFtgLcLHABEARQApYkOxFCng5YkOMzw//PkZFckShjkBXsvDIAAA0gAAAAAIMd5WPAiuBAhTphRyDJf4jwDXfwChPFsim63xmQcRiMincgxgynrOwPWdSRVQxvmRjDwAPVORAQ0Rgh7mwQXNgishGozIxvmRjjM7ZFZ4FY8AZLJDtEh2eQwjrPArHgajyTEBlnB4ZnB0Szv5AoD+SZ/JMHqUHu8lneBPzh9BPRIdgoD+FM8B6h2PACEKEHoHrO/DXmh2iXxSlY8AKDHCerHh2iQ7RIZG4gasaoRwa2hO5BUx4doks7wO8iIkCscUyseBWPDtEl3EykVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVRaEZ/FG5jBkRmYIJAZCMMFwYAOsBDppiQQqBU6Ipe5d6aqaTkKXKqtcV0vFvGJNxh9lrcn7Za3J+2uvFDC6npewDwnlAGxfVg1E4jA1//PkZE0jIhzwCW8MHgAAA0gAAAAALhGEEqKAbF8WgkZoAJEtBBEwNiSXDcESQWSUnNRKL46rhSHwIjgHwSkgPglEAKQmEsKQ6J4Uh0I4HgVGwjByOgBhPHQAEaBkCI8C4ESQWjpOTUz560+7x0qMWCclcXNNnrUa2Bs9ZiXQxLtYPoI1sEbOWaJKldd1q61k6eZqye0eaOWFRJUrrutUe46PqtPmLZ6mfPUz56mcPkri5mJdDGyyOI6pkZihOro2jJDRLoY1sEdauphKiXQxWaOidC8t6FbBGtYdXNutXdabTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//PkZAAZfhzC3z0mjgAAA0gAAAAAB+Tkktu1lwcIuxMzQQtUI9ULaFKVkdvcWlpr/NJ3sKWHSHAjuJMQnFF1G2DRKRHTqi7DzJEQljhdATnjQpEQydKI0B8yKiEscLoGzxMKSIqdKI2D5KKhCNB4ugNniYUgsDoOiAViQeEoWEIPA8IxQTniYUkQyMjBGYPsokJYsXQPZaVWVKlEbtmpo4uNynZ3a8qWdmeN////zuzsz/f/////////lOzOz5s07s+bNSzPF5snFllXF5Us25uUacWXFwtEkaUUfCakiJwGTEFNRTMuMTAwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq';

let contextoAudio = null;
let bufferAudioDecodificado = null;
let promessaDecodificacao = null;
let somHabilitado = true;
let ultimoMomentoReproducaoRolagem = 0;
const INTERVALO_MINIMO_REPRODUCAO_MS = 1200;

/**
 * Obtém ou inicializa o AudioContext global após interação do usuário.
 * @returns {AudioContext|null}
 */
function obterContextoAudio() {
  if (!contextoAudio && typeof window !== 'undefined') {
    const AudioContextClass = window.AudioContext || window.webkitAudioContext;
    if (AudioContextClass) {
      contextoAudio = new AudioContextClass();
    }
  }
  if (contextoAudio && contextoAudio.state === 'suspended') {
    contextoAudio.resume().catch(() => {});
  }
  return contextoAudio;
}

/**
 * Converte a string base64 do áudio MP3 em um ArrayBuffer para decodificação nativa.
 * @returns {ArrayBuffer}
 */
function obterArrayBufferAudio() {
  const binaryString = atob(AUDIO_ROLAGEM_BASE64);
  const len = binaryString.length;
  const bytes = new Uint8Array(len);
  for (let i = 0; i < len; i++) {
    bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes.buffer;
}

/**
 * Retorna o AudioBuffer decodificado, usando cache em memória para reprodução instantânea.
 * @param {AudioContext} ctx 
 * @returns {Promise<AudioBuffer|null>}
 */
async function obterBufferDecodificado(ctx) {
  if (bufferAudioDecodificado) {
    return bufferAudioDecodificado;
  }
  if (promessaDecodificacao) {
    return promessaDecodificacao;
  }

  promessaDecodificacao = new Promise((resolve) => {
    try {
      const arrayBuffer = obterArrayBufferAudio();
      ctx.decodeAudioData(
        arrayBuffer,
        (decoded) => {
          bufferAudioDecodificado = decoded;
          resolve(decoded);
        },
        (erro) => {
          console.warn('[ReadyToRoll] Falha ao decodificar MP3 via Web Audio:', erro);
          resolve(null);
        }
      );
    } catch (err) {
      console.warn('[ReadyToRoll] Erro ao instanciar decodeAudioData:', err);
      resolve(null);
    }
  });

  return promessaDecodificacao;
}

/**
 * Toca o som procedural sintético como fallback de emergência caso a reprodução do MP3 falhe.
 * @param {AudioContext} ctx 
 */
function tocarImpactoProcedural(ctx) {
  try {
    const agora = ctx.currentTime;
    for (let i = 0; i < 4; i++) {
      const tempo = agora + (i === 0 ? 0 : 0.07 + Math.random() * 0.05 + i * 0.03);
      const duracao = 0.04;
      const bufferRuido = ctx.createBuffer(1, ctx.sampleRate * duracao, ctx.sampleRate);
      const dados = bufferRuido.getChannelData(0);
      for (let j = 0; j < dados.length; j++) {
        dados[j] = (Math.random() * 2 - 1) * Math.exp(-j / (ctx.sampleRate * 0.008));
      }
      const fonte = ctx.createBufferSource();
      fonte.buffer = bufferRuido;
      const filtro = ctx.createBiquadFilter();
      filtro.type = 'bandpass';
      filtro.frequency.setValueAtTime(650 + Math.random() * 300, tempo);
      filtro.Q.setValueAtTime(3.5, tempo);
      const ganho = ctx.createGain();
      ganho.gain.setValueAtTime(Math.pow(0.7, i) * 0.5, tempo);
      ganho.gain.exponentialRampToValueAtTime(0.001, tempo + duracao);
      fonte.connect(filtro);
      filtro.connect(ganho);
      ganho.connect(ctx.destination);
      fonte.start(tempo);
      fonte.stop(tempo + duracao);
    }
  } catch (_) {}
}

/**
 * Reproduz o áudio real de dados rolando (freesound_community-rpg-dice-rolling-95182.mp3).
 * @param {number} [_quantidadeImpactos=4] Parâmetro mantido por compatibilidade.
 */
export async function tocarSomRolagem(_quantidadeImpactos = 4) {
  // Ignora se a aba estiver em segundo plano para evitar ecos entre múltiplas abas
  if (typeof document !== 'undefined' && document.hidden) return;

  dispararFeedbackHaptico([15, 35, 20]);
  if (!somHabilitado) return;

  // Trava de segurança contra disparos repetidos em rajada / ecos de rede
  const agoraMs = Date.now();
  if (agoraMs - ultimoMomentoReproducaoRolagem < INTERVALO_MINIMO_REPRODUCAO_MS) {
    return;
  }
  ultimoMomentoReproducaoRolagem = agoraMs;

  try {
    const ctx = obterContextoAudio();
    if (ctx) {
      const buffer = await obterBufferDecodificado(ctx);
      if (buffer) {
        const fonte = ctx.createBufferSource();
        fonte.buffer = buffer;
        const ganho = ctx.createGain();
        ganho.gain.setValueAtTime(0.9, ctx.currentTime);
        fonte.connect(ganho);
        ganho.connect(ctx.destination);
        fonte.start(0);
        return;
      }
      // Fallback procedural
      tocarImpactoProcedural(ctx);
      return;
    }
  } catch (erroWebAudio) {
    console.warn('[ReadyToRoll] Erro no Web Audio API, tentando fallback HTML5 Audio:', erroWebAudio);
  }

  // Fallback secundário usando elemento HTML5 Audio
  try {
    const audio = new Audio('data:audio/mp3;base64,' + AUDIO_ROLAGEM_BASE64);
    audio.volume = 0.9;
    audio.play().catch(() => {});
  } catch (_) {}
}

/**
 * Dispara feedback háptico no dispositivo móvel (se suportado pelo navegador).
 * @param {number|number[]} padrao 
 */
export function dispararFeedbackHaptico(padrao = [18, 35, 22]) {
  try {
    if (typeof navigator !== 'undefined' && typeof navigator.vibrate === 'function') {
      navigator.vibrate(padrao);
    }
  } catch {
    // Ignora silenciosamente caso o dispositivo ou navegador restrinja vibração
  }
}

/**
 * Dispara um toque háptico ultracurto para cliques em botões.
 */
export function dispararCliqueTabilHaptico() {
  dispararFeedbackHaptico(12);
}

/**
 * Alterna a ativação do áudio.
 * @param {boolean} ativo 
 */
export function configurarSom(ativo) {
  somHabilitado = Boolean(ativo);
}

export function obterEstadoSom() {
  return somHabilitado;
}
